### ISSUE TITLE
Feature request: Count of unique entities

### ISSUE THREAD

**Issue by nicoleharris** [TERENA/met#2]
Would be useful to be able to see a count of the unique entities within MET as many of the SPs / IdPs are duplicated across federations.

**Comment by biancini** [comment]
Nicole, don't get the meaning of this question.
On met homepage we have counters under "Entities summary"
Entities	15743
IDP		5838
SP		9907
This is not what you're asking for?
What could be a solution to satisfy your request?
Thanks

**Comment by nicoleharris** [comment]
Hey Andrea

So I am assuming that the total of entities includes each instance of
the entity - so all 23 instances of
https://met.refeds.org/met/entity/http%253A%252F%252Fshibboleth.ebscohost.com/
plus all 20 instances of
https://met.refeds.org/met/entity/https%253A%252F%252Fsp.tshhosting.com%252Fshibboleth/
etc.  Is that right?

I was wondering if it would be possible to calculate also the number of
unique entities across the federations (so only counting Ebscohost once
etc). 

Does that make sense?

Cheers

Nicole

On 11/05/2015 10:33, Andrea Biancini wrote:
>
> Nicole, don't get the meaning of this question.
> On met homepage we have counters under "Entities summary"
> Entities 15743
> IDP 5838
> SP 9907
> This is not what you're asking for?
> What could be a solution to satisfy your request?
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TERENA/met/issues/2#issuecomment-100833005>.
>

-- 
Nicole Harris
Project Development Officer
GÉANT Association Amsterdam Office (formerly TERENA)
Singel 468 D, 1017 AW Amsterdam
The Netherlands
Skype: harrisnv
M:+31 64 610 53 95

**Comment by biancini** [comment]
Yes it makes sense.
I was sure the totals where not double-counting, but I did the math and... well it is happening.
It's a good idea to fix!

**Comment by biancini** [comment]
Now sums should be correct!
In fact the totals are lower than the sum of all federation's count (as expected).
Will do some more cross check, but the computation logic seems right.
