### ISSUE TITLE
Discovery broken

### ISSUE THREAD

**Issue by nckroy** [TERENA/met#41]
I'm trying to change the logo for InCommon in MET. When I try to login, I get to the discovery interface, pick Internet2's IdP, and then MET freezes up and never redirects me to the IdP.

**Comment by nckroy** [comment]
OK so discovery just worked, but was very slow (to the point of creating a couple expired sessions while I was waiting). Now I can't edit InCommon's logo. What do I need to do to be able to set a logo for InCommon?

**Comment by biancini** [comment]
I added you as editor of InCommon federation so you should now be able to add a logo. Or you can send it here for me to upload it in met.

Regarding the problem during authentication, I have no idea why that happened. I am not experiencing similar problems. I've tried to pick Internet2 IdPs and redirect happened in a reasonable time...

**Comment by nckroy** [comment]
Thanks - how do I upload the logo? I clicked on InCommon Federation and got to the page where it says no logo, am logged in as nroy@internet2.edu, but could not see a way to upload the logo. Thanks!

**Comment by biancini** [comment]
You should have an "Edit" button on the top of the page

[screenshot_20181101-222116](https://user-images.githubusercontent.com/1561585/47880886-cf207580-de24-11e8-8b18-a0ecd88d8238.jpg)

**Comment by nckroy** [comment]
Thanks, that worked.

Nick
