### ISSUE TITLE
SURFconext SPs do not belong to SURFconext federation

### ISSUE THREAD

**Issue by surfnet-niels** [TERENA/met#42]
Even though MET reports SURFconext federation to be the registrar of e.g. ORCID entity (https://met.refeds.org/met/entity/https%253A%252F%252Forcid.org%252Fsaml2%252Fsp%252F1/),
SURFconext federation itself is not listed as the federation the SP is a member of.
This seems the be the case for all SPs in SURFconext

**Comment by biancini** [comment]
The URL used to download SURFconect metadata in MET is:
https://engine.surfconext.nl/authentication/proxy/idps-metadata?sp-entity-id=https://profile.surfconext.nl/authentication/metadata
is it the right URL?
In this metadata I don't see ORCID (actually it only describes IdPs)... should I add another URL to the federation? Which one?

**Comment by thijskh** [comment]
This is the IdPs URL (actually, was; it's now `https://metadata.surfconext.nl/idps-metadata.xml` and I have updated that in MET).

There is no SPs URL currently since this serves no technical purpose in our federation setup.

**Comment by nicoleharris** [comment]
As there is no SP url, we cannot unfortunately help with this issue so will close.
