### ISSUE TITLE
entityID=https://sdauth.sciencedirect.com/ metadata in CARSI is not consistent with that at https://www.carsi.edu.cn/carsimetadata/carsifed-metadata.xml.

### ISSUE THREAD

**Issue by lbxll** [TERENA/met#44]
entityID=https://sdauth.sciencedirect.com/ metadata in CARSI is not consistent with that at https://www.carsi.edu.cn/carsimetadata/carsifed-metadata.xml. Can anybody help check?

**Comment by meshna** [comment]
Dear Developer, the CARSI federation metadata is stale in explorer tool, our SP metadata (entityID=https://sdauth.sciencedirect.com/) has been updated in it over a month ago. Can you please fix that?

**Comment by nicoleharris** [comment]
Hi - I've updated the database and this now seems to be correct. Apologies for the error!
