### ISSUE TITLE
Removed entity still present in MET

### ISSUE THREAD

**Issue by bmonticini** [TERENA/met#46]
Dear MET support,
today I found that the following entity: https://idem.unisa.it/idp/shibboleth
which has been removed from IDEM feed on November 2018
is still present in MET.
It seems that removed entities are not properly updated.

Thank you in advance
Barbara

**Comment by nicoleharris** [comment]
Hi Barbara
I've updated the entities and this seems to now be resolved.  Many thanks!
Nicole
