### ISSUE TITLE
Add FriendlyName to OIDs

### ISSUE THREAD

**Issue by nicoleharris** [TERENA/met#7]
Request from Thomas L at SWITCH: 

I noticed that MET does only display OIDs for unknown attributes like the ones from the swissEduPerson schema, despite the FriendlyName is included in metadata.

See the example e.g. here: https://met.refeds.org/met/entity/https%253A%252F%252Ffsso.springer.com/?federation=switchaai-federation

It would be nice if for such unknown attributes the FriendlyName could be appended in parentheses.

So it would like this
 - urn:oid:2.16.756.1.2.5.1.1.4 (swissEduPersonHomeOrganization)
instead of just this
 - urn:oid:2.16.756.1.2.5.1.1.4

In case of a missing FriendlyName it could be displayed as
 - urn:oid:2.16.756.1.2.5.1.1.4 (?)
to make it clear that no further information is available.

The most extreme example is probably the SWITCH attribute viewer with all out national and locally defined attributes listed: https://met.refeds.org/met/entity/https%253A%252F%252Fattribute-viewer.aai.switch.ch%252Fshibboleth/

**Comment by biancini** [comment]
Now the visualization is as requested.
For the SWITCH attribute viewer now MET shows:
* urn:oid:1.3.6.1.4.1.25178.1.2.10 (schacHomeOrganizationType)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.11 (eduPersonAssurance)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.10 (eduPersonTargetedID)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.13 (eduPersonUniqueId)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.16 (eduPersonOrcid)
* urn:oid:2.16.756.1.2.5.1.1.12 (swissEduPersonCardUID)
* urn:oid:2.16.756.1.2.5.1.1.13 (swissEduID)
* urn:oid:2.16.756.1.2.5.1.1.10 (swissEduPersonStaffCategory)
* urn:oid:2.16.756.1.2.5.1.1.11 (swissEduPersonMatriculationNumber)
* urn:oid:0.9.2342.19200300.100.1.39 (homePostalAddress)
* urn:oid:2.5.4.11 (ou)
* urn:oid:2.16.840.1.113730.3.1.241 (displayName)
* urn:oid:1.3.6.1.4.1.5923.1.5.1.1 (isMemberOf)
* urn:oid:1.3.6.1.4.1.22865.10.1.1.19 (unibasChRoles)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.9 (eduPersonScopedAffiliation)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.8 (eduPersonPrimaryOrgUnitDN)
* urn:oid:2.16.756.1.2.5.1.1.1023 (swissLibraryPersonAffiliation)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.1 (eduPersonAffiliation)
* urn:oid:2.5.4.16 (postalAddress)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.3 (eduPersonOrgDN)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.2 (eduPersonNickname)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.5 (eduPersonPrimaryAffiliation)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.4 (eduPersonOrgUnitDN)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.7 (eduPersonEntitlement)
* urn:oid:1.3.6.1.4.1.5923.1.1.1.6 (eduPersonPrincipalName)
* urn:oid:1.3.6.1.4.1.11817.1.1.2.27 (uzhSapUserIdStaff)
* urn:oid:2.16.840.1.113730.3.1.39 (preferredLanguage)
* urn:oid:2.16.756.1.2.5.1.1.1013 (fhnwOeID)
* urn:oid:2.16.756.1.2.5.1.1.1012 (fhnwUPN)
* urn:oid:2.16.840.1.113730.3.1.3 (employeeNumber)
* urn:oid:2.16.756.1.2.5.1.1.1010 (fhnwSapUserID)
* urn:oid:2.16.756.1.2.5.1.1.1014 (ASVZ)
* urn:oid:2.16.756.1.2.5.1.1.8 (swissEduPersonStudyBranch3)
* urn:oid:2.16.756.1.2.5.1.1.9 (swissEduPersonStudyLevel)
* urn:oid:2.16.756.1.2.5.1.1.3 (swissEduPersonGender)
* urn:oid:1.3.6.1.4.1.11817.1.1.2.13 (uzhSapUserId)
* urn:oid:2.5.4.3 (commonName)
* urn:oid:2.16.756.1.2.5.1.1.1 (swissEduPersonUniqueID)
* urn:oid:2.16.756.1.2.5.1.1.2 (swissEduPersonDateOfBirth)
* urn:oid:1.3.6.1.4.1.25178.1.2.9 (schacHomeOrganization)
* urn:oid:2.16.756.1.2.5.1.1.4 (swissEduPersonHomeOrganization)
* urn:oid:2.16.756.1.2.5.1.1.5 (swissEduPersonHomeOrganizationType)
* urn:oid:2.16.756.1.2.5.1.1.6 (swissEduPersonStudyBranch1)
* urn:oid:2.5.4.4 (surname)
* urn:oid:0.9.2342.19200300.100.1.41 (mobile)
* urn:oid:2.16.756.1.2.5.1.1.7 (swissEduPersonStudyBranch2)
* urn:oid:2.16.756.1.2.5.1.1.1011 (fhnwSapUserInfo)
* urn:oid:0.9.2342.19200300.100.1.20 (homePhone)
* urn:oid:2.5.4.42 (givenName)
* urn:oid:0.9.2342.19200300.100.1.3 (email)
* urn:oid:0.9.2342.19200300.100.1.1 (uid)
* urn:oid:2.16.756.1.2.5.1.1.1022 (Shib-Custom-UserType)
* urn:oid:2.16.756.1.2.5.1.1.1009 (fhnwIDPerson)
* urn:oid:2.5.4.20 (telephoneNumber)
* urn:oid:2.16.756.1.2.5.1.1.1000 (UniBEapplAuthorisation)
* urn:oid:2.16.756.1.2.5.1.1.1001 (AAA-UsageLimit)
* urn:oid:1.3.6.1.4.1.7165.2.1.15 (primaryGroupID)
* urn:oid:2.16.756.1.2.5.1.1.1003 (unilMemberOf)
* urn:oid:2.16.756.1.2.5.1.1.1004 (unige.ch-OuCode)
* urn:oid:2.16.756.1.2.5.1.1.1006 (unilFacultePrincipale)
